- name: This play book for creating VPC subnets instances
  hosts: local
  connection: local
  gather_facts: False
  vars_files:
    - secret.yml
    - variable.yml
  tasks:
  - name: create VPC
    ec2_vpc_net:
      name: "{{ vpc_name[1] }}"
      cidr_block: "{{ vpc_cidr[1] }}"
      region: "{{ region[1] }}"
      state: present
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_key_id }}"
    register: ec2_vpc_net_result

  - name: create subnet to the vpc
    ec2_vpc_subnet:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_key_id }}"
      vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
      region: "{{ region[1] }}"
      cidr: "{{ subnet_cidr[1] }}"
      state: present
      map_public: yes
      resource_tags:
        Name: "{{ subnet_name[1] }}"
    register: subnet


  - name: create key pair using key_material obtained using 'file' lookup plugin
    amazon.aws.ec2_key:
      name: my_keypair
      key_material: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"
      region: "{{ region[1] }}"
      state: present
        #  register: my_keypair

