- name: host-configuration
  hosts: nginx
  tasks:
  - name: install apache
    apt:
         name: apache2
         state: present
  - name: start apache
    service:
         name: apache2
         state: started
         enabled: yes
