- name: This play book for creating VPC subnets instances
  hosts: local
  connection: local
  gather_facts: False
  vars_files:
    - secret.yml
    - variable.yml
  tasks:
  - name: create key pair using key_material obtained using 'file' lookup plugin
    amazon.aws.ec2_key:
      name: my_keypair
      key_material: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"  
      region: "{{ region[1] }}"
      state: present
        
