- name: This play book for creating peering connection
  hosts: local
  connection: local
  gather_facts: False
  vars_files:
    - secret.yml
    - variable.yml
  tasks:
  - name: create key pair using key_material obtained using 'file' lookup plugin
    amazon.aws.ec2_key:
      name: "{{ vpc_name[0] }}"
      name: my_keypair
      key_material: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"
      region: "{{ region[0] }}"
      state: absent
    register: keypair
       
       
# update the CIDR address in the SSH port section.
       
  - name: Create Security Group
    ec2_group:
      name: Web DMZ
      description: DMZ Security Group
      name: "{{ vpc_name[0] }}"
      region: "{{ region[0] }}"
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_key_id }}"
      state: absent
      rules:
        - proto: tcp
          ports:
          - 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports:
          - 22
          cidr_ip: 0.0.0.0/0

       
  - name: create subnet to the vpc
    ec2_vpc_subnet:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_key_id }}"
      region: "{{ region[0] }}"
      name: "{{ vpc_name[0] }}"
      cidr: "{{ subnet_cidr[0] }}"
      state: absent
      map_public: yes
      resource_tags:
        Name: "{{ subnet_name[0] }}"

  - name: create VPC
    ec2_vpc_net:
      name: "{{ vpc_name[0] }}"
      cidr_block: "{{ vpc_cidr[0] }}"
      region: "{{ region[0] }}"
      state: absent
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_key_id }}"


  - name: Create Ec2 instance
    amazon.aws.ec2:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_key_id }}"
      image: ami-0fa49cc9dc8d62c84
      wait: yes
      instance_type: t2.micro
      region: "{{ region[1] }}"
        # group_id: "{{ security.group_id }}"
      vpc_subnet_id: "{{ subnet.subnet.id }}"
      key_name: "{{ key_name.keypair }}"
      assign_public_ip: no
      instance_tags:
        app: ansible-vm2-rohan
      count_tag:
        Name: "{{ ec2_tag[1] }}"
      exact_count: 1
    register: ec2vm2
     
